name: sms_gateway
description: "SMS Forwarder App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  telephony_plus: ^0.0.4  # مكتبة حديثة تدعم Android v2 embedding
  http: ^1.1.0

flutter:
  uses-material-design: true
